version: '3.8'

services:
  treeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    command: python -m treeline
    ports:
      - "8000:8000"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: tox
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app

  docs:
    build:
      context: .
      dockerfile: Dockerfile
    command: sphinx-build -b html docs/source docs/build/html
    volumes:
      - .:/app
      - ./docs:/app/docs
    ports:
      - "8080:8080"

  lint:
    build:
      context: .
      dockerfile: Dockerfile
    command: tox -e lint
    volumes:
      - .:/app

  coverage:
    build:
      context: .
      dockerfile: Dockerfile
    command: tox -e coverage
    volumes:
      - .:/app
      - ./output:/app/output
