name: Python Quality Check & Release

on:
  push:
    branches:
      - "**" 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install package and tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest flake8 black isort "black[jupyter]"
          
      - name: Format code
        run: |
          black .
          isort .
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: auto-format with black and isort"
          
      - name: Run tests
        run: |
          pytest tests/
          
      - name: Build documentation
        run: |
          pip install sphinx sphinx-rtd-theme
          make html

  create_release:
    needs: quality
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false